//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using System.Collections.Generic;

namespace ScheduleReminder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlarmsJson {
            get {
                return ((string)(this["AlarmsJson"]));
            }
            set {
                this["AlarmsJson"] = value;
            }
        }


        public List<Alarm> Alarms
        {
            get
            {
                var list = JsonConvert.DeserializeObject<List<Alarm>>(AlarmsJson);
                if(list == null)
                {
                    list = new List<Alarm>();
                }
                return list;
            }
            set
            {
                AlarmsJson = JsonConvert.SerializeObject(value);
            }
        }
    }
}
